In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
path =  '/content/drive/MyDrive/Colab Notebooks/input_data/results.csv'

In [4]:
path_2 = 'results.csv'

In [5]:
df = pd.read_csv(path_2)

In [6]:
df.head(10)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
5,6,18,6,3,8,13,6,6,6,3.0,57,\N,\N,50,14,1:29.639,212.974,11
6,7,18,7,5,14,17,7,7,7,2.0,55,\N,\N,54,8,1:29.534,213.224,5
7,8,18,8,6,1,15,8,8,8,1.0,53,\N,\N,20,4,1:27.903,217.180,5
8,9,18,9,2,4,2,\N,R,9,0.0,47,\N,\N,15,9,1:28.753,215.100,4
9,10,18,10,7,12,18,\N,R,10,0.0,43,\N,\N,23,13,1:29.558,213.166,3

In [7]:
df.dtypes

resultId             int64
raceId               int64
driverId             int64
constructorId        int64
number              object
grid                 int64
position            object
positionText        object
positionOrder        int64
points             float64
laps                 int64
time                object
milliseconds        object
fastestLap          object
rank                object
fastestLapTime      object
fastestLapSpeed     object
statusId             int64
dtype: object

In [8]:
df.isnull().sum()

resultId           0
raceId             0
driverId           0
constructorId      0
number             0
grid               0
position           0
positionText       0
positionOrder      0
points             0
laps               0
time               0
milliseconds       0
fastestLap         0
rank               0
fastestLapTime     0
fastestLapSpeed    0
statusId           0
dtype: int64

In [9]:
df.describe()

,resultId,raceId,driverId,constructorId,grid,positionOrder,points,laps,statusId
count,26759.000000,26759.000000,26759.000000,26759.000000,26759.000000,26759.000000,26759.000000,26759.000000,26759.000000
mean,13380.977391,551.687283,278.673530,50.180537,11.134796,12.794051,1.987632,46.301768,17.224971
std,7726.134642,313.265036,282.703039,61.551498,7.202860,7.665951,4.351209,29.496557,26.026104
min,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000
25%,6690.500000,300.000000,57.000000,6.000000,5.000000,6.000000,0.000000,23.000000,1.000000
50%,13380.000000,531.000000,172.000000,25.000000,11.000000,12.000000,0.000000,53.000000,10.000000
75%,20069.500000,811.000000,399.500000,63.000000,17.000000,18.000000,2.000000,66.000000,14.000000
max,26764.000000,1144.000000,862.000000,215.000000,34.000000,39.000000,50.000000,200.000000,141.000000

In [10]:
wins = df[df['positionOrder']==1]

In [11]:
races = pd.read_csv('races.csv')

In [12]:

print(df.shape, wins.shape)

(26759, 18) (1128, 18)

In [13]:
merged = pd.merge(wins, races[['raceId','year']], how='inner',on='raceId')

In [14]:
merged.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,year
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1,2008
1,23,19,8,6,1,2,1,1,1,10.0,56,1:31:18.555,5478555,37,2,1:35.405,209.158,1,2008
2,45,20,13,6,2,2,1,1,1,10.0,57,1:31:06.970,5466970,38,3,1:33.600,208.153,1,2008
3,67,21,8,6,1,1,1,1,1,10.0,66,1:38:19.051,5899051,46,1,1:21.670,205.191,1,2008
4,89,22,13,6,2,1,1,1,1,10.0,58,1:26:49.451,5209451,16,3,1:26.666,221.734,1,2008

In [15]:
wins_per_season = merged.groupby(['year','driverId'])['positionOrder'].count().reset_index()

In [16]:
wins_per_season.head()

   year  driverId  positionOrder
0  1950       579              3
1  1950       593              1
2  1950       642              3
3  1951       498              1
4  1951       579              3

In [17]:
wins_per_season.columns = ['year', 'driverId', 'wins']

In [18]:
wins_per_season.head()

   year  driverId  wins
0  1950       579     3
1  1950       593     1
2  1950       642     3
3  1951       498     1
4  1951       579     3

In [19]:
wins_per_season['rank'] = wins_per_season.groupby('year')['wins'].rank(method='dense', ascending=False)

In [20]:
wins_per_season.head()

   year  driverId  wins  rank
0  1950       579     3   1.0
1  1950       593     1   2.0
2  1950       642     3   1.0
3  1951       498     1   3.0
4  1951       579     3   1.0

In [21]:
top3 = wins_per_season[wins_per_season['rank']<=3].sort_values(['year','wins'], ascending=[False,False])

In [22]:
print(top3.head(20))

     year  driverId  wins  rank
397  2024       830     9   1.0
400  2024       846     4   2.0
399  2024       844     3   3.0
394  2023       830    19   1.0
393  2023       815     2   2.0
395  2023       832     1   3.0
389  2022       830    15   1.0
391  2022       844     3   2.0
388  2022       815     2   3.0
386  2021       830    10   1.0
382  2021         1     8   2.0
383  2021       815     1   3.0
384  2021       817     1   3.0
385  2021       822     1   3.0
387  2021       839     1   3.0
377  2020         1    11   1.0
379  2020       822     2   2.0
380  2020       830     2   2.0
378  2020       815     1   3.0
381  2020       842     1   3.0

In [23]:
drivers = pd.read_csv('drivers.csv')

In [26]:
drivers['driverName'] = drivers['forename'] + ' ' + drivers['surname']

In [27]:
top_3_drivers = top3.merge(drivers[['driverId', 'driverName']], on='driverId').sort_values(['year','wins'], ascending=[False,False])

In [28]:
top_3_drivers.head(10)

   year  driverId  wins  rank       driverName
0  2024       830     9   1.0   Max Verstappen
1  2024       846     4   2.0     Lando Norris
2  2024       844     3   3.0  Charles Leclerc
3  2023       830    19   1.0   Max Verstappen
4  2023       815     2   2.0     Sergio Pérez
5  2023       832     1   3.0     Carlos Sainz
6  2022       830    15   1.0   Max Verstappen
7  2022       844     3   2.0  Charles Leclerc
8  2022       815     2   3.0     Sergio Pérez
9  2021       830    10   1.0   Max Verstappen